name = "pawsdel-wkr-1"
main = "src/worker.js"
compatibility_date = "2026-08-20"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "pawsdel"
database_id = "94bd4880-b104-4e32-8733-6bfbc90a42d9"

[triggers]
crons = ["*/5 * * * *", "*/30 * * * *"]
